# Generated by Django 4.2 on 2023-05-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooftop_rabbitry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rabbit",
            name="images",
            field=models.FileField(
                default="RooftopRabbitry/rooftop_rabbitry/static/images/default.jpg",
                upload_to="RooftopRabbitry/rooftop_rabbitry/static/images/",
            ),
        ),
    ]
