# Generated by Django 4.2 on 2023-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooftop_rabbitry", "0002_rabbit_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="rabbitbreed",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="rabbit",
            name="images",
            field=models.ImageField(
                default="RooftopRabbitry/rooftop_rabbitry/static/images/default.jpg",
                upload_to="RooftopRabbitry/rooftop_rabbitry/static/images/",
            ),
        ),
    ]
