# Generated by Django 4.2 on 2023-05-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooftop_rabbitry", "0003_rabbitbreed_description_alter_rabbit_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rabbit",
            old_name="images",
            new_name="image",
        ),
    ]
